name: "Sh module bundler"
description: "Bundles third-party modules into an Odoo.sh deployment repo"

inputs:
  repo:
    description: "Source repository (org/repo)"
    required: true
  target_branch:
    description: "Branch to push compiled addons to in the deployment repo"
    required: true
  event_type:
    description: "trigger_staging_build or trigger_production_build"
    required: true
  base_branch:
    description: "Base branch of the code repo to fetch config files from"
    required: true
  git_user_name:
    description: "Git user name to use for pushing to repo"
  git_user_email:
    description: "Git user email to use for pushing to repo"
  alt_repo:
    description: "Alternative repository (org/repo) to optionally push the build result to"
    required: false
  alt_repo_target_branch:
    description: "Branch to push to in the alt repo. Defaults to target_branch"
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/impress-foods/sh-module-bundler:latest"
